config/routes.rb
Rails.application.routes.draw do
  resources :maps
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  post '/csv_dl/:id', to: 'users#csv_dl', as: :csv_dl
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      
      get 'logs'
      get 'logs_month'
      get 'logs_day'
      get 'start'
      get 'places'
      
    end
  end
  
  resources :plans
  patch 'plans/:id', to: 'plans#update', as: :update_plan
  patch 'modal/:id', to: 'plans#update_modal', as: :update_modal
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :plans, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_token, nil)
  end
  
  def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      User.where(['name LIKE ?', "%#{search}%"])
    else
      User.all #全て表示。
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy,:logs,:logs_month,:logs_day,:start,:csv_dl]
  before_action :logged_in_user, only: [:index, :show,:start,:places, :logs, :logs_month, :logs_day,:csv_dl,:edit_action,:edit, :update]
  before_action :correct_user, only: [:show,:start,:logs_month,:logs_day,:edit_action,:edit, :update]
  before_action :admin_user, only: [:destroy,:index]

  def index
    @users = User.all.page(params[:page]).search(params[:search])
  end

  def show
  end
  
  def start
    @plan = @user.plans
    @plans = @user.plans.where(finished_at: nil).order(id: "DESC")
  end
  
  def places
    @plan = Plan.find(params[:id])
  end
  
  def logs
    @menu_sum = @user.plans.where.not(created_at: nil).count #存在しているplanの数
    @plans = @user.plans.order(created_at: "DESC").search(params[:search])
    @frees = @user.plans.where(menu: ['フリー'])
    @frees_sum = 0
    @studys = @user.plans.where(menu: ['勉強'])
    @studys_sum =0
    @sports = @user.plans.where(menu: ['運動'])
    @sports_sum =0
    @jobs = @user.plans.where(menu: ['仕事'])
    @jobs_sum =0
    @meals = @user.plans.where(menu: ['食事'])
    @meals_sum =0
    @sleeps = @user.plans.where(menu: ['睡眠'])
    @sleeps_sum =0
  end
  
  def logs_month
    @month_first = params[:date].nil? ?
    Time.current.beginning_of_month : params[:date].to_time #○/1だけ非表示になるためTimeクラス
    @month_last = @month_first.end_of_month.to_time
    @plans = @user.plans.where(created_at: @month_first..@month_last).order(created_at: "DESC").search(params[:search])
    @frees = @user.plans.where(created_at: @month_first..@month_last,menu: ['フリー'])
    @frees_sum = 0
    @studys = @user.plans.where(created_at: @month_first..@month_last,menu: ['勉強'])
    @studys_sum =0
    @sports = @user.plans.where(created_at: @month_first..@month_last,menu: ['運動'])
    @sports_sum =0
    @jobs = @user.plans.where(created_at: @month_first..@month_last,menu: ['仕事'])
    @jobs_sum =0
    @meals = @user.plans.where(created_at: @month_first..@month_last,menu: ['食事'])
    @meals_sum =0
    @sleeps = @user.plans.where(created_at: @month_first..@month_last,menu: ['睡眠'])
    @sleeps_sum =0
  end
  
  def logs_day
    @today_first = params[:date].nil? ?
    Time.current.beginning_of_day : params[:date].to_time
    @today_last = @today_first.end_of_day.to_time
    @plans = @user.plans.where(created_at: @today_first..@today_last).order(created_at: "DESC").search(params[:search])
    @frees = @user.plans.where(created_at: @today_first..@today_last,menu: ['フリー'])
    @frees_sum = 0
    @studys = @user.plans.where(created_at: @today_first..@today_last,menu: ['勉強'])
    @studys_sum =0
    @sports = @user.plans.where(created_at: @today_first..@today_last,menu: ['運動'])
    @sports_sum =0
    @jobs = @user.plans.where(created_at: @today_first..@today_last,menu: ['仕事'])
    @jobs_sum =0
    @meals = @user.plans.where(created_at: @today_first..@today_last,menu: ['食事'])
    @meals_sum =0
    @sleeps = @user.plans.where(created_at: @today_first..@today_last,menu: ['睡眠'])
    @sleeps_sum =0
  end
  
  def csv_dl
    @lists = @user.plans.order(created_at: "DESC")
    
    respond_to do |format|
      # format.html do
      #     #html用の処理を書く
      # end 
      format.csv do
          send_data render_to_string, filename: "#{@user.name}logs.csv", type: :csv
      end
    end
  end
  
  def edit_action
    @active_id = params[:id] #idを取得し@active_idに代入
    @user = Active.find(params[:id]).user #userレコードからactiveモデルのidを取得し、@userに代入
    @dates = @user.actives.find(@active_id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit      
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end

    def basic_info_params
      params.require(:user).permit(:department, :basic_time, :work_time)
    end

    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_logs_index.html.erb
<tbody>
      <tr>
        <th>メニュー</th>
        <th>開始時間</th>
        <th>終了時間</th>
        <th>合計時間</th>
        <th>メモ</th>
      <% if current_user.admin? || current_user?(@user)%>
        <th>場所</th>
        <th>編集</th>
        <th>削除</th>
      <% end %>
      </tr>
    </tbody>
    
    <tfoot>
      <% @plans.each do |plan|%>
      <tr>
        <td><%=plan.menu %></td>
        <td><%= plan.created_at.strftime("%Y年%m月%d日 %H:%M")%></td>
        <td><%= plan.finished_at.strftime("%Y年%m月%d日 %H:%M") if plan.finished_at.present? %></td>
        <td>
          <% if plan.created_at.present? && plan.finished_at.present? %>
          <%= working_times(plan.created_at, plan.finished_at) %>
          <% seconds = (plan.finished_at - plan.created_at).to_i %>
          <% @total_seconds = @total_seconds.to_i + seconds %>
          <% else plan.created_at.present? && plan.finished_at.nil? %>
          <%= working_times(plan.created_at, Time.current) %>
          <% end %>
        </td>
        <td><%= plan.note%></td>
        
        <% if current_user.admin? || current_user?(@user)%>
        <td><% if plan.prefectures.present? %>
          <%= link_to(places_user_path(plan),target: :_blank) do %>
        <i class="fa fa-map-marker fa-2x  btn button_map"></i>
        <% end %>
        <% end %>
        </td>
        
        <td><%= link_to(edit_plan_path(plan), remote: true) do %>
        <i class="fa fa-edit fa-2x btn button_edit"></i>
        <% end %>
        </td>
        
        <td><%= link_to(plan, method: :delete,data: { confirm: "削除してよろしいですか？" }) do%>
        <i class="fa fa-trash fa-2x btn button_delete"></i>
        <% end %>
        </td>
        <% end %>
      </tr>
      <% end %>
      
      <tr>
        <td>合計数</td>
        <td><%=@plans.count%></td>
        <td>累計時間</td>
        <td><%= working_times_sum(@total_seconds) unless @total_seconds.nil? %></td>
        <td></td>
        <% if current_user.admin? %>
        <td></td>
        <td></td>
        <td></td>
        <% end %>
      </tr>
    </tfoot>

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧") %>
<div class="center">
<div class = "test">ユーザー一覧</div>
</div>
<%= paginate @users %>
<%= form_with(scope: :search, url: users_path, method: :get, local: true) do |f| %>
  <%= text_field_tag :search,"",{class: "search-form"}%>
  <%= submit_tag '検索', :name => nil, class: "btn search-btn"%>
<% end %>
<div class = "center">
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <theader>
      <tr>
        <th>名前</th>
        <th>現在状況</th>
          <th>削除</th>
      </tr>
    </theader>
    <tbody>
      <% @users.each do |user| %>
      <tr>
      <td><%= link_to user.name, logs_user_path(user) %></td>
      <td><% if user.plans.any?{|plan|
         (plan.created_at.present? &&
         plan.finished_at.blank?)} %>
         <%="実行中.."%>
         <% end %>
      </td>
      <td>
        <% unless user.admin %>
         <%= link_to(user, method: :delete,data: { confirm: "削除してよろしいですか？" }) do %>
         <i class="fa fa-trash fa-2x btn button_delete"></i>
        <% end %>
       <% end %><!--unless user.admin-->
      </td>
      <% end %><!--@users.each-->
      </tr>
    </tbody>
</table>
</div>

<%= paginate @users %>


<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Microposts</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- コード追加　Font Awesome読み込みコード-->
　　 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>
  
  <!--モーダルウインドウ表示-->
<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/logs.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>名前：<%= @user.name %></td>
    </tr>
    <tr>
      <% if @user.plans.any?{|plan|
         (plan.created_at.present? &&
         plan.finished_at.blank?)} %>
         <td>アクション：<%="実行中.."%></td>
         <% end %>
    </tr>
  </table>
</div>

<% if current_user?(@user) %>
<div class="center">
  <div class="row">
    <div class="col-sm-1">
      <%= link_to "全て", logs_user_path(current_user), class: "btn day" %>
    </div>
    <div class="col-sm-1">
      <%= link_to "月別", logs_month_user_path(current_user), class: "btn day" %>
    </div>
    <div class="col-sm-1">
      <%= link_to "日別", logs_day_user_path(current_user), class: "btn day" %>
    </div>
  </div>
  <div class = "center">
      <%= link_to "アクション作成", start_user_path(current_user), class: "btn start" %>
  </div>
</div>
<% end %>

<% if @plans.present? %>
<div>
    <thead>
      <!--Chart.js表示-->
      <div class="chart-container" style="position: relative; height:50vh; width:80vw center">
        <canvas id="myChart"></canvas>
      </div>
    </thead>
    
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <% if current_user?(@user) || current_user.admin? %>
    <%= link_to " CSV出力", csv_dl_path(format: :csv), class: "btn csv fa fa-arrow-circle-o-down fa-lg", method: :post %>
    <% end %>
    <%= form_with(scope: :search, url: logs_user_path, method: :get, local: true) do |f| %>
  <%= select_tag :search, options_for_select([["",""],["フリー","フリー"], ["勉強","勉強"], ["運動","運動"], ["仕事","仕事"], ["食事","食事"], ["睡眠","睡眠"]],:selected=>"6"),
  { autofocus: 'true', class: 'search-form'} %>
  <%= submit_tag '検索', :menu => nil, class: "btn search-btn"%>
<% end %>
    <%= render 'logs_index' %>
    
  </table>
</div>
<% end %>

<!--モーダルウインドウ表示-->
<div id="edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<!--Chart.js表示-->
<!--フリー合計時間-->
<% @frees.each do |free|%>
     <% if free.finished_at.present? %>
          <% seconds = (free.finished_at - free.created_at).to_i %>
          <% @frees_sum = @frees_sum.to_i + seconds %>
     <% end %>
    <% end %>
<!--勉強合計時間-->
<% @studys.each do |study|%>
     <% if study.finished_at.present? %>
      <% seconds = (study.finished_at - study.created_at).to_i %>
          <% @studys_sum = @studys_sum.to_i + seconds %>
     <% end %>
    <% end %>
<!--運動合計時間-->
<% @sports.each do |sport|%>
     <% if sport.finished_at.present? %>
      <% seconds = (sport.finished_at - sport.created_at).to_i %>
          <% @sports_sum = @sports_sum.to_i + seconds %>
     <% end %>
    <% end %>
<!--仕事合計時間-->
<% @jobs.each do |job|%>
     <% if job.finished_at.present? %>
      <% seconds = (job.finished_at - job.created_at).to_i %>
          <% @jobs_sum = @jobs_sum.to_i + seconds %>
     <% end %>
    <% end %>
<!--食事合計時間-->
<% @meals.each do |meal|%>
     <% if meal.finished_at.present? %>
      <% seconds = (meal.finished_at - meal.created_at).to_i %>
          <% @meals_sum = @meals_sum.to_i + seconds %>
     <% end %>
    <% end %>
<!--睡眠合計時間-->
<% @sleeps.each do |sleep|%>
     <% if sleep.finished_at.present? %>
      <% seconds = (sleep.finished_at - sleep.created_at).to_i %>
          <% @sleeps_sum = @sleeps_sum.to_i + seconds %>
     <% end %>
    <% end %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.min.js"></script>
<script>
                    var dataLabelPlugin = {
                        afterDatasetsDraw: function (chart, easing) {
                            // To only draw at the end of animation, check for easing === 1
                            var ctx = chart.ctx;

                            chart.data.datasets.forEach(function (dataset, i) {
                                var dataSum = 0;
                                dataset.data.forEach(function (element){
                                    dataSum += element;
                                });

                                var meta = chart.getDatasetMeta(i);
                                if (!meta.hidden) {
                                    meta.data.forEach(function (element, index) {
                                        // Draw the text in black, with the specified font
                                        ctx.fillStyle = 'rgb(255, 255, 255)';

                                        var fontSize = 12;
                                        var fontStyle = 'normal';
                                        var fontFamily = 'Helvetica Neue';
                                        ctx.font = Chart.helpers.fontString(fontSize, fontStyle, fontFamily);

                                        // Just naively convert to string for now
                                        var labelString = chart.data.labels[index];
                                        var dataString = (Math.round(dataset.data[index] / dataSum * 1000)/10).toString() + "%";

                                        // Make sure alignment settings are correct
                                        ctx.textAlign = 'center';
                                        ctx.textBaseline = 'middle';

                                        var padding = 5;
                                        var position = element.tooltipPosition();
                                        ctx.fillText(labelString, position.x, position.y - (fontSize / 2) - padding);
                                        ctx.fillText(dataString, position.x, position.y + (fontSize / 2) - padding);
                                    });
                                }
                            });
                        }
                    };
                   
                    // Chart
                    var myChart1 = "myChart";
                    var chart = new Chart(myChart1, {
                        type: 'pie',
                        data: {
                            labels: ["フリー", "勉強", "運動", "仕事", "食事", "睡眠"],
                            datasets: [{
                                label: "Sample",
                                backgroundColor: ["#5D99FF", "#FA8072", "#FFD700", "#9ACD32", "#9370DB", "#F4A460"],
                                data: [
                                <%= working_times_sum(@frees_sum) %>,
                                <%= working_times_sum(@studys_sum) %>,
                                <%= working_times_sum(@sports_sum) %>,
                                <%= working_times_sum(@jobs_sum) %>,
                                <%= working_times_sum(@meals_sum) %>,
                                <%= working_times_sum(@sleeps_sum) %>],
                            }]
                        },
                        options: {
                            title: {
                                display: true,
                                text: "割合"
                            },
                            legend:{
                            },
                            maintainAspectRatio: false,
                        },
                        plugins: [dataLabelPlugin],
                    });
</script>

app/views/users/logs_day.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>名前：<%= @user.name %></td>
    </tr>
    <tr>
      <% if @user.plans.any?{|plan|
         (plan.created_at.present? &&
         plan.finished_at.blank?)} %>
         <td>アクション：<%="実行中.."%></td>
         <% end %>
    </tr>
  </table>
</div>
<div class="center">
  <div class="row">
    <div class="col-sm-1">
      <%= link_to "全て", logs_user_path(current_user), class: "btn day" %>
    </div>
    <div class="col-sm-1">
      <%= link_to "月別", logs_month_user_path(current_user), class: "btn day" %>
    </div>
    <div class="col-sm-1">
      <%= link_to "日別", logs_day_user_path(current_user), class: "btn day" %>
    </div>
  </div><!--row-->
  <div class = "center">
      <%= link_to "アクション作成", start_user_path(current_user), class: "btn start" %>
  </div><!--center-->
  
</div><!--center-->
<div class="center">
  <%= link_to(logs_day_user_path(date: @today_first.prev_day)) do %>
    <i class="fa fa-arrow-left fa-lg page-left" %></i><% end %>
    <%= @today_first.strftime("%m月%d日")%>
    <%= link_to(logs_day_user_path(date: @today_first.next_day)) do %>
    <i class="fa fa-arrow-right fa-lg page-right" %></i>
    <% end %>
</div>

<% if @plans.present? %>
<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <!--Chart.js表示-->
      <div class="chart-container" style="position: relative; height:50vh; width:80vw">
        <canvas id="myChart"></canvas>
      </div>
    </thead>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <%= form_with(scope: :search, url: logs_day_user_path, method: :get, local: true) do |f| %>
  <%= select_tag :search, options_for_select([["",""],["フリー","フリー"], ["勉強","勉強"], ["運動","運動"], ["仕事","仕事"], ["食事","食事"], ["睡眠","睡眠"]],:selected=>"6"),
  { autofocus: 'true', class: 'search-form'} %>
  <%= submit_tag '検索', :menu => nil, class: "btn search-btn"%>
<% end %>
    <%= render 'logs_index' %>
    
  </table>
</div>
<% end %>

<!--モーダルウインドウ表示-->
<div id="edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<!--Chart.js表示-->
<!--フリー合計時間-->
<% @frees.each do |free|%>
     <% if free.finished_at.present? %>
          <% seconds = (free.finished_at - free.created_at).to_i %>
          <% @frees_sum = @frees_sum.to_i + seconds %>
     <% end %>
    <% end %>
<!--勉強合計時間-->
<% @studys.each do |study|%>
     <% if study.finished_at.present? %>
      <% seconds = (study.finished_at - study.created_at).to_i %>
          <% @studys_sum = @studys_sum.to_i + seconds %>
     <% end %>
    <% end %>
<!--運動合計時間-->
<% @sports.each do |sport|%>
     <% if sport.finished_at.present? %>
      <% seconds = (sport.finished_at - sport.created_at).to_i %>
          <% @sports_sum = @sports_sum.to_i + seconds %>
     <% end %>
    <% end %>
<!--仕事合計時間-->
<% @jobs.each do |job|%>
     <% if job.finished_at.present? %>
      <% seconds = (job.finished_at - job.created_at).to_i %>
          <% @jobs_sum = @jobs_sum.to_i + seconds %>
     <% end %>
    <% end %>
<!--食事合計時間-->
<% @meals.each do |meal|%>
     <% if meal.finished_at.present? %>
      <% seconds = (meal.finished_at - meal.created_at).to_i %>
          <% @meals_sum = @meals_sum.to_i + seconds %>
     <% end %>
    <% end %>
<!--睡眠合計時間-->
<% @sleeps.each do |sleep|%>
     <% if sleep.finished_at.present? %>
      <% seconds = (sleep.finished_at - sleep.created_at).to_i %>
          <% @sleeps_sum = @sleeps_sum.to_i + seconds %>
     <% end %>
    <% end %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.min.js"></script>
<script>
                    var dataLabelPlugin = {
                        afterDatasetsDraw: function (chart, easing) {
                            // To only draw at the end of animation, check for easing === 1
                            var ctx = chart.ctx;

                            chart.data.datasets.forEach(function (dataset, i) {
                                var dataSum = 0;
                                dataset.data.forEach(function (element){
                                    dataSum += element;
                                });

                                var meta = chart.getDatasetMeta(i);
                                if (!meta.hidden) {
                                    meta.data.forEach(function (element, index) {
                                        // Draw the text in black, with the specified font
                                        ctx.fillStyle = 'rgb(255, 255, 255)';

                                        var fontSize = 12;
                                        var fontStyle = 'normal';
                                        var fontFamily = 'Helvetica Neue';
                                        ctx.font = Chart.helpers.fontString(fontSize, fontStyle, fontFamily);

                                        // Just naively convert to string for now
                                        var labelString = chart.data.labels[index];
                                        var dataString = (Math.round(dataset.data[index] / dataSum * 1000)/10).toString() + "%";

                                        // Make sure alignment settings are correct
                                        ctx.textAlign = 'center';
                                        ctx.textBaseline = 'middle';

                                        var padding = 5;
                                        var position = element.tooltipPosition();
                                        ctx.fillText(labelString, position.x, position.y - (fontSize / 2) - padding);
                                        ctx.fillText(dataString, position.x, position.y + (fontSize / 2) - padding);
                                    });
                                }
                            });
                        }
                    };
                   
                    // Chart
                    var myChart1 = "myChart";
                    var chart = new Chart(myChart1, {
                        type: 'pie',
                        data: {
                            labels: ["フリー", "勉強", "運動", "仕事", "食事", "睡眠"],
                            datasets: [{
                                label: "Sample",
                                backgroundColor: ["#5D99FF", "#FA8072", "#FFD700", "#9ACD32", "#9370DB", "#F4A460"],
                                data: [
                                <%= working_times_sum(@frees_sum) %>,
                                <%= working_times_sum(@studys_sum) %>,
                                <%= working_times_sum(@sports_sum) %>,
                                <%= working_times_sum(@jobs_sum) %>,
                                <%= working_times_sum(@meals_sum) %>,
                                <%= working_times_sum(@sleeps_sum) %>],
                            }]
                        },
                        options: {
                            title: {
                                display: true,
                                text: "割合"
                            },
                            legend:{
                            },
                            maintainAspectRatio: false,
                        },
                        plugins: [dataLabelPlugin],
                    });
</script>

app/views/users/show.html.erb
<!DOCTYPE html>
<% provide(:title, "メニュー") %>
<div class="container center">
  <div class = "test">メニュー一覧</div>
  <div class="row">
    <div class="col-md-6">
      <%= link_to (root_path) do %>
        <i class="fa fa-home fa-5x btn home"></i>
        <p>ホーム</p>
        <% end %>
    </div>
    
    <div class="col-md-6">
      <%= link_to (edit_user_path(current_user)) do %>
        <i class="fa fa-child fa-5x btn user-edit"></i>
        <p>プロフィール編集</p>
        <% end %>
    </div>
    </div>
    
    <% if current_user.admin %>
    
    <div class="row">
      <div class="col-md-6">
       <%= link_to (start_user_path(current_user)) do %>
        <i class="fa fa-clock-o fa-5x btn user-start"></i>
        <p>アクション作成</p>
        <% end %>
    </div>
    
    <div class="col-md-6">
      <%= link_to (logs_user_path(current_user)) do %>
        <i class="fa fa-pie-chart fa-5x btn user-logs"></i>
        <p>集計</p>
        <% end %>
    </div>
    </div>
    
    <div class="row">
      <div class="col-md-6">
      <%= link_to (users_path) do %>
        <i class="fa fa-users fa-4x btn user-index"></i>
        <p>ユーザー一覧</p>
        <% end %>
    </div>
    
    <div class="col-md-6">
      <%= link_to logout_path, method: :delete do %>
        <i class="fa fa-power-off fa-5x btn logout"></i>
        <p>ログアウト</p>
        <% end %>
    </div>
    </div>
    
    <% else %>
    
    <div class="row">
      <div class="col-md-6">
       <%= link_to (start_user_path(current_user)) do %>
        <i class="fa fa-clock-o fa-5x btn user-start"></i>
        <p>アクション作成</p>
        <% end %>
    </div>
    
    <div class="col-md-6">
      <%= link_to (logs_user_path(current_user)) do %>
        <i class="fa fa-pie-chart fa-5x btn user-logs"></i>
        <p>集計</p>
        <% end %>
    </div>
    </div>
    
    <div class="col">
      <%= link_to logout_path, method: :delete do %>
        <i class="fa fa-power-off fa-5x btn logout"></i>
        <p>ログアウト</p>
        <% end %>
    </div>
   </div><!--class="row"-->
   
  <% end %>
</div>