config/routes.rb
Rails.application.routes.draw do
  resources :maps
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  post '/csv_dl/:id', to: 'users#csv_dl', as: :csv_dl
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      
      get 'logs'
      get 'logs_month'
      get 'logs_day'
      get 'start'
      get 'places'
      
    end
  end
  
  resources :plans
  patch 'plans/:id', to: 'plans#update', as: :update_plan
  patch 'modal/:id', to: 'plans#update_modal', as: :update_modal
  
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default navbar-light" style="background-color: #F4A460;">
  <div class="container">
    <b><i><%= link_to "Time-Active", root_path, id: "logo" %></i></b>
    <nav>
      <b><i><ul class="nav navbar-nav navbar-right">
        <% unless logged_in? %>
          <li><%= link_to "ホーム", root_path %></li>
          <li><%= link_to "ログイン", login_path %></li>
        <% else %>
          <li><%= link_to current_user.name, user_path(current_user) %></li>
          <li><%= link_to "アクション作成", start_user_path(current_user) %></li>
          <li><%= link_to "集計", logs_user_path(current_user) %></li>
          <li><%= link_to "ユーザー一覧", users_path if current_user.admin%></li>
        <% end %>
      </ul></i></b>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    
    <%= favicon_link_tag('time-active_image2') %>
    
  </head>
  <body>
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>